modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="ices_mod"
version="1.4"
displayName="Ice's Mod"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Made by Autism itself"
authors="Icefighter"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.ices_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration